repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files # prevents giant files from being committed.
    -   id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
    -   id: check-merge-conflict # checks for files that contain merge conflict strings.
    -   id: trailing-whitespace # trims trailing whitespace.
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: detect-private-key # detects the presence of private keys.


-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
            - "--in-place"
            - "--remove-unused-variables"
            - "--remove-all-unused-imports"
            - "--ignore-init-module-imports"
# -   repo: https://github.com/PyCQA/pylint
#     rev: v3.0.0a6
#     hooks:
#     -   id: pylint
#         args:
#             - "--disable=unused-argument"