"""Add Notification, NotificationTemplate table

Revision ID: 32add570a29f
Revises: 5a0e5ac86823
Create Date: 2023-04-04 01:38:11.094264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32add570a29f'
down_revision = '5a0e5ac86823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
