"""Add Group, GR_Member table

Revision ID: 5a0e5ac86823
Revises: 6b2309daf787
Create Date: 2023-04-04 01:37:48.901506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0e5ac86823'
down_revision = '6b2309daf787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group',
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.Column('room_uuid', sa.UUID(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_uuid'], ['MatchingRoom.room_uuid'], ),
    sa.PrimaryKeyConstraint('group_uuid')
    )
    op.create_table('GR_Member',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_uuid'], ['Group.group_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.user_uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'group_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GR_Member')
    op.drop_table('Group')
    # ### end Alembic commands ###
