"""Add Notification, NotificationTemplate table

Revision ID: 6b2309daf787
Revises: a64c440de50a
Create Date: 2023-04-04 01:36:40.582110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2309daf787'
down_revision = 'a64c440de50a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
