"""Add MR_Member table

Revision ID: 720954a6d8c7
Revises: 
Create Date: 2023-04-04 01:33:43.162196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720954a6d8c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MR_Member',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('room_uuid', sa.UUID(), nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leave_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_left', sa.Boolean(), nullable=False),
    sa.Column('is_bound', sa.Boolean(), nullable=False),
    sa.Column('bind_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bind_uuid'], ['BindUser.bind_uuid'], ),
    sa.ForeignKeyConstraint(['room_uuid'], ['MatchingRoom.room_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['User.user_uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'room_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MR_Member')
    # ### end Alembic commands ###
