"""Add MR_Liked_Hated_Member table

Revision ID: 8c5bdd75dd78
Revises: d50d56ca8cc3
Create Date: 2023-04-04 01:51:10.798823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5bdd75dd78'
down_revision = 'd50d56ca8cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MR_Liked_Hated_Member',
    sa.Column('member_uuid', sa.UUID(), nullable=False),
    sa.Column('target_member_uuid', sa.UUID(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.Column('is_hated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_uuid'], ['MR_Member.member_uuid'], ),
    sa.ForeignKeyConstraint(['target_member_uuid'], ['MR_Member.member_uuid'], ),
    sa.PrimaryKeyConstraint('member_uuid', 'target_member_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MR_Liked_Hated_Member')
    # ### end Alembic commands ###
