"""Add GR_Member table

Revision ID: a64c440de50a
Revises: 720954a6d8c7
Create Date: 2023-04-04 01:35:10.206516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c440de50a'
down_revision = '720954a6d8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
