"""Add is_active to User table

Revision ID: cdd99b69c07a
Revises: 9c1bc9a2093e
Create Date: 2023-04-02 12:17:50.544696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd99b69c07a'
down_revision = '9c1bc9a2093e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_active')
    # ### end Alembic commands ###
