"""user table password set nullable and add is_google_sso column

Revision ID: fd49f0eea2b2
Revises: c2e93411c48c
Create Date: 2023-04-05 02:58:55.931317

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd49f0eea2b2"
down_revision = "c2e93411c48c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("is_google_sso", sa.Boolean(), nullable=True))
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("User", "is_google_sso")
    # ### end Alembic commands ###
